name: todo
description: Todo Sample

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.7.0
  freezed_annotation: ^2.2.0
  drift: ^2.5.0
  path_provider: ^2.0.12
  path: ^1.8.2
  flutter_riverpod: ^2.1.3
  desktop_window: ^0.4.0

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  json_serializable: ^6.6.0
  freezed: ^2.3.2
  drift_dev: ^2.4.1
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

